export default {
  content: [
    "./index.html",
    "./admin.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#0b1c30",
        "surface-tint": "#005db7",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#4b454a",
        "on-secondary-fixed": "#1f1a1e",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#00468c",
        "secondary": "#635c61",
        "on-secondary-container": "#686066",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed": "#eae0e6",
        "on-tertiary-container": "#fefcff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#e7dde3",
        "tertiary": "#545c72",
        "on-primary": "#ffffff",
        "tertiary-container": "#6c748b",
        "primary-container": "#0073df",
        "tertiary-fixed": "#dae2fd",
        "on-surface-variant": "#414754",
        "inverse-primary": "#a9c7ff",
        "outline": "#717786",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed-dim": "#bec6e0",
        "on-primary-container": "#fefcff",
        "primary-fixed-dim": "#a9c7ff",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#cec4ca",
        "surface-bright": "#f8f9ff",
        "primary": "#005bb3",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "surface": "#f8f9ff",
        "on-surface": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-primary-fixed": "#001b3d",
        "on-tertiary-fixed": "#131b2e",
        "on-tertiary": "#ffffff",
        "background": "#f8f9ff",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c0c6d6",
        "error": "#ba1a1a",
        "surface-container-high": "#dce9ff",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-padding": "64px",
        "gutter": "48px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "sidebar-width": "320px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "headline-sm": ["18px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
